# Generated by Django 5.2.5 on 2025-08-17 10:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIMetrics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=10)),
                ('request_count', models.BigIntegerField(default=0)),
                ('error_count', models.BigIntegerField(default=0)),
                ('avg_response_time_ms', models.FloatField(default=0.0)),
                ('min_response_time_ms', models.FloatField(default=0.0)),
                ('max_response_time_ms', models.FloatField(default=0.0)),
                ('date', models.DateField(auto_now_add=True)),
                ('last_request_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=512)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Custom metadata fields')),
            ],
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finding_type', models.CharField(help_text='Type of risk finding', max_length=100)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('risk_score', models.FloatField(help_text='Risk score from 0-10')),
                ('evidence_text', models.TextField(help_text='Text evidence supporting the finding')),
                ('page_number', models.IntegerField(help_text='Page where finding was detected')),
                ('char_start', models.IntegerField(help_text='Start character position in page text')),
                ('char_end', models.IntegerField(help_text='End character position in page text')),
                ('recommendation', models.TextField(blank=True)),
                ('compliance_impact', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('detection_model', models.CharField(blank=True, max_length=100)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_findings', to='contract_api.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('page_number', models.IntegerField()),
                ('text', models.TextField(help_text='Full text extracted from this page')),
                ('text_chunks', models.JSONField(default=list, help_text='Text chunks for vector search')),
                ('chunk_embeddings', models.JSONField(default=list, help_text='Vector embeddings for chunks')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='contract_api.document')),
            ],
        ),
        migrations.CreateModel(
            name='ExtractedFields',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parties', models.JSONField(default=list, help_text='List of party information with name, type, address')),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('term', models.CharField(blank=True, help_text='Contract term/duration', max_length=255)),
                ('termination_date', models.DateField(blank=True, null=True)),
                ('governing_law', models.CharField(blank=True, max_length=100)),
                ('payment_terms', models.TextField(blank=True)),
                ('auto_renewal', models.BooleanField(blank=True, null=True)),
                ('auto_renewal_notice_days', models.IntegerField(blank=True, null=True)),
                ('confidentiality', models.TextField(blank=True)),
                ('indemnity', models.TextField(blank=True)),
                ('liability_cap_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('liability_cap_currency', models.CharField(blank=True, help_text='ISO currency code', max_length=3)),
                ('signatories', models.JSONField(default=list, help_text='List of signatories with name, title, date')),
                ('contract_type', models.CharField(blank=True, max_length=100)),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('value_currency', models.CharField(blank=True, max_length=3)),
                ('extraction_confidence', models.FloatField(blank=True, null=True)),
                ('extracted_at', models.DateTimeField(auto_now_add=True)),
                ('extraction_model', models.CharField(blank=True, max_length=100)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_fields', to='contract_api.document')),
            ],
        ),
    ]
