# Generated by Django 5.2.5 on 2025-08-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractedfields',
            name='confidentiality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedfields',
            name='contract_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extractedfields',
            name='governing_law',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='extractedfields',
            name='indemnity',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedfields',
            name='liability_cap_currency',
            field=models.CharField(blank=True, help_text='ISO currency code', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='extractedfields',
            name='payment_terms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extractedfields',
            name='term',
            field=models.CharField(blank=True, help_text='Contract term/duration', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='extractedfields',
            name='value_currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
